title: My Portfolio
description: A portfolio of projects and things I have made.
url: "https://yat44.github.io"
baseurl: "/my-portfolio-site" 

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme